# Generated by Django 5.1.3 on 2025-01-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shope',
            name='edit_pin',
            field=models.IntegerField(default=1234),
        ),
    ]
