# Generated by Django 5.1.3 on 2025-02-22 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0002_shope_edit_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shope_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('payment_type', models.CharField(max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('shope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunil.shope')),
            ],
        ),
    ]
