# Generated by Django 5.1.3 on 2025-01-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_farmer_payment_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_cash_transition',
            name='farmer_bill',
        ),
        migrations.RemoveField(
            model_name='farmer_cash_transition',
            name='office_employee',
        ),
        migrations.RemoveField(
            model_name='farmer_cash_transition',
            name='shope',
        ),
        migrations.RemoveField(
            model_name='farmer_phonepe_transition',
            name='farmer_bill',
        ),
        migrations.RemoveField(
            model_name='farmer_phonepe_transition',
            name='office_employee',
        ),
        migrations.RemoveField(
            model_name='farmer_phonepe_transition',
            name='shope',
        ),
        migrations.DeleteModel(
            name='Farmer_bank_transition',
        ),
        migrations.DeleteModel(
            name='Farmer_cash_transition',
        ),
        migrations.DeleteModel(
            name='Farmer_Phonepe_transition',
        ),
    ]
