# Generated by Django 5.1.3 on 2025-03-09 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_company_services'),
        ('sunil', '0004_alter_shope_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_sell_opning_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('type', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.company')),
                ('shope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.shope')),
            ],
        ),
    ]
