# Generated by Django 5.1.3 on 2025-03-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_company_sell_opning_balance'),
        ('sunil', '0004_alter_shope_payment_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_sell_opning_balance',
            new_name='Company_opning_balance',
        ),
    ]
